AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ControlPortAddress:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  AssociateControlPort:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: "3306"
      NetworkInterfaceId: Ref controlXface
  WebPortAddress:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  AssociateWebPort:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: "192.168.0.12"
      NetworkInterfaceId: Ref LaunchTemplateName:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateName: launch-template-2   
      LaunchTemplateData2: 
        BlockDeviceMappings: 
          - Ebs:
              VolumeSize: 22
              VolumeType: gp2
              DeleteOnTermination: true
              Encrypted: true
            DeviceName: /dev/xvdcuz
        CreditSpecification: 
          CpuCredits: Unlimited
        Monitoring: 
          Enabled: true
        ImageId: ami-063a9ea2ff5685f7fubuntu
        InstanceType: c3.large
        KeyName: MyKeyPair2
        SecurityGroupIds: 
          - sg-0762a24ffec5ca84d  
