AWSTemplateFormatVersion: 2010-09-09

Resources:
  Topic:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Join
        - '-'
        - - 'mystoragas3'
          - !Ref 'AWS::AccountId' 
