AWSTemplateFormatVersion: 2010-09-09
Outputs:
  ARN:
    Description: "Standalone policy"
    Export:
      Name: Thoushall
    Value: 10
Parameters:
  UsernameID:
    Type: String
Resources:
  Policy:
    Properties:
      Groups:
        - Administrators
      PolicyDocument:
        Statement:
          -
            Action:
              - "cloudformation:Describe*"
              - "cloudformation:List*"
              - "cloudformation:Get*"
              - "s3:Get*"
              - "s3:List*"
              - "s3-object-lambda:Get*"
              - "s3-object-lambda:List*"
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: Thoushall
    Type: "AWS::IAM::Policy"
  S3Bucket:
    Properties:
      BucketName: mystorages3
    Type: "AWS::S3::Bucket"
  User:
    Properties:
      Groups: Administrators
      LoginProfile: dezo
      Policies: Thoushall
      UserName: UsernameID
    Type: "AWS::IAM::User"
