AWSTemplateFormatVersion: 2010-09-09


Resources:
  Apppipelines:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: dafirstci-cd
      RestartExecutionOnUpdate: True
      ArtifactStore:
        Type: S3 
        Location:
          Ref: ArtifactStoreS3Location 
        EncryptionKey:
          Id: arn:aws:kms:useast-1:ACCOUNT-ID:key/KEY-ID
          Type: KMS
      DisableInboundStageTransitions: 
      - 
        StageName: Release 
        Reason: "Disabling the transition until integration tests are completed"
      RoleArn:
        Ref: CodePipelineServiceRole 
      Tags:
        - Key: Project
          Value: ProjectA
        - Key: IsContainerBased
          Value: 'true'
      Stages: 
      - 
        Name: Source 
        Actions:  
          - 
            Name: SourceAction 
            InputArtifacts: 
              -
                Name: SourceOutput 
            ActionTypeId: 
              Category: Deploy 
              Owner: AWS 
              Version: 1 
              Provider: CodeDeploy
            Configuration: 
              ApplicationName: 
                Ref: Stelligent 
              DeploymentGroupName: 
                Ref: DeploymentGroupName  
            Trigger:
   	 	branches:
    		  include:
    		    - master
    		    - releases/*
   		  exclude:
   		    - releases/old*
	     RunOrder: 1
      - 
        Name: Deploy
        Actions: 
          - 
            Name: DeployAction
            InputArtifacts: 
              - 
                Name: DeployOutput 
            ActionTypeId: 
              Category: Deploy 
              Owner: AWS 
              Version: 1
              Provider: CodeDeploy 
            Configuration: 
              ApplicationName: 
                Ref: Stelligent
              DeploymentGroupName: 
                Ref: DeploymentGroupName 
            RunOrder: 2 
  Policy:
    Properties:
      Groups:
        - Administrators
      PolicyDocument:
        Statement:
          -
            Action:
              - "codedeploy:CreateDeployment"
              - "codedeploy:GetDeployment"
              - "codedeploy:GetApplication"
              - "codedeploy:GetApplicationRevision"
              - "codedeploy:RegisterApplicationRevision"
              - "codedeploy:GetDeploymentConfig"
              - "ecs:RegsiterTaskDefinition"
              - "s3:Get*"
              - "s3:List*"
              - "s3-object-lambda:Get*"
              - "s3-object-lambda:List*"
            Effect: Allow
            Resource: "arn:aws:iam::324320755747:user/desmond.ndambi.labs"
        Version: "2012-10-17"
      PolicyName: Thoushould
    Type: "AWS::IAM::Policy"
  S3bucket:
    Type: AWS::S3::Bucket
    Properties:
       BucketName: ArtifactStoreS3Location
  
